include: 
  - server/server.yaml
  - bloggen-frontend/frontend.yaml

services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend 

volumes:
  post-volume:
    driver: local
    driver_opts:
      type: none
      device: ./bloggen-frontend/app/static
      o: bind